﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace ConsoleApp1
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"ID", @"ID"),new InputOutputColumnPair(@"DOZ", @"DOZ"),new InputOutputColumnPair(@"TOPLAM", @"TOPLAM")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"SEHIR", @"SEHIR"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"ID",@"DOZ",@"TOPLAM",@"SEHIR"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=5,MinimumExampleCountPerLeaf=6,NumberOfTrees=7,MaximumBinCountPerFeature=353,LearningRate=0.0694693781576546F,FeatureFraction=1F,LabelColumnName=@"NUFUS",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
