
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                ID = 1F,
                SEHIR = @"ADANA",
                DOZ = 355404F,
                TOPLAM = 1139868F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual NUFUS with predicted NUFUS from sample data...\n\n");


            Console.WriteLine($"ID: {1F}");
            Console.WriteLine($"SEHIR: {@"ADANA"}");
            Console.WriteLine($"DOZ: {355404F}");
            Console.WriteLine($"TOPLAM: {1139868F}");
            Console.WriteLine($"NUFUS: {2258718F}");


            Console.WriteLine($"\n\nPredicted NUFUS: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
